# Kubernates Deployment.yaml for creating deployment in azure kubernates service(AKS)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurekubedemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurekubedemo
  template:
    metadata:
      labels:
        app : azurekubedemo  
    spec:
      containers:
      - name: azurekubedemo
        image: ravindrakumarch/angkubedemo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

# Kubernate Service.yaml for creating service in AKS
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: aks-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: aks-port-name
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app : azurekubedemo