apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: my-service
spec:
  type: NodePort
  ports:
  - name: service-port-name
    port: 80
    targetPort: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app : angkubedemo