apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: my-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app : angkubedemo